[2016-11-22 17:20:13.3823] System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at yidascan.DataAccess.DataAccess.Query(String sql, SqlParameter[] p) in E:\ljework\yida\codesource\yidascan\DataAccess\DataAccess.cs:line 56
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20, select IndexNo,Name,Code,Class,Remark from OPCParam  order by IndexNo DESC
[2016-11-22 17:20:13.6323] 启动opc失败.
System.NullReferenceException: Object reference not set to an instance of an object.
   at yidascan.FrmMain.StartOpc() in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 81
   at yidascan.FrmMain..ctor() in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 41
[2016-11-22 17:20:14.2644] 初始化失败。
System.NullReferenceException: Object reference not set to an instance of an object.
   at yidascan.FrmMain.BindDgv() in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 97
   at yidascan.FrmMain.FrmMain_Load(Object sender, EventArgs e) in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 58
[2016-11-22 17:20:37.1537] System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at yidascan.DataAccess.DataAccess.Query(String sql, SqlParameter[] p) in E:\ljework\yida\codesource\yidascan\DataAccess\DataAccess.cs:line 56
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20, select IndexNo,Name,Code,Class,Remark from OPCParam  order by IndexNo DESC
[2016-11-22 17:20:37.2677] 启动opc失败.
System.NullReferenceException: Object reference not set to an instance of an object.
   at yidascan.FrmMain.StartOpc() in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 81
   at yidascan.FrmMain..ctor() in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 41
[2016-11-22 17:20:37.7147] 初始化失败。
System.NullReferenceException: Object reference not set to an instance of an object.
   at yidascan.FrmMain.BindDgv() in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 97
   at yidascan.FrmMain.FrmMain_Load(Object sender, EventArgs e) in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 58
[2016-11-22 17:20:49.7394] 关闭连接失败！
[2016-11-22 17:20:52.5335] 关闭连接失败！
[2016-11-22 17:20:53.9696] 关闭连接失败！
[2016-11-22 17:20:57.9749] 关闭连接失败！
[2016-11-22 17:20:59.9590] 关闭连接失败！
[2016-11-22 17:21:34.4049] 关闭连接失败！
[2016-11-22 17:21:40.0823] 关闭连接失败！
[2016-11-22 17:21:43.9365] 关闭连接失败！
[2016-11-22 17:25:20.5709] System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at yidascan.DataAccess.DataAccess.Query(String sql, SqlParameter[] p) in E:\ljework\yida\codesource\yidascan\DataAccess\DataAccess.cs:line 56
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20, select IndexNo,Name,Code,Class,Remark from OPCParam  order by IndexNo DESC
[2016-11-22 17:25:20.7039] 启动opc失败.
System.NullReferenceException: Object reference not set to an instance of an object.
   at yidascan.FrmMain.StartOpc() in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 81
   at yidascan.FrmMain..ctor() in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 41
[2016-11-22 17:25:21.1929] 初始化失败。
System.NullReferenceException: Object reference not set to an instance of an object.
   at yidascan.FrmMain.BindDgv() in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 97
   at yidascan.FrmMain.FrmMain_Load(Object sender, EventArgs e) in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 58
[2016-11-22 17:26:16.4621] 关闭连接失败！
[2016-11-22 17:26:20.5293] 关闭连接失败！
[2016-11-22 17:54:30.5500] System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at yidascan.DataAccess.DataAccess.Query(String sql, SqlParameter[] p) in E:\ljework\yida\codesource\yidascan\DataAccess\DataAccess.cs:line 56
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20, select IndexNo,Name,Code,Class,Remark from OPCParam  order by IndexNo DESC
[2016-11-22 17:54:30.6748] 启动opc失败.
System.NullReferenceException: Object reference not set to an instance of an object.
   at yidascan.FrmMain.StartOpc() in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 81
   at yidascan.FrmMain..ctor() in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 41
[2016-11-22 17:54:30.8776] 初始化失败。
System.NullReferenceException: Object reference not set to an instance of an object.
   at yidascan.FrmMain.BindDgv() in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 97
   at yidascan.FrmMain.FrmMain_Load(Object sender, EventArgs e) in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 58
[2016-11-22 17:54:56.0561] 关闭连接失败！
[2016-11-22 17:55:06.0557] 关闭连接失败！
[2016-11-22 17:55:18.9569] 关闭连接失败！
[2016-11-22 17:55:23.3249] 关闭连接失败！
[2016-11-22 17:58:04.7326] System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at yidascan.DataAccess.DataAccess.Query(String sql, SqlParameter[] p) in E:\ljework\yida\codesource\yidascan\DataAccess\DataAccess.cs:line 56
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20, select IndexNo,Name,Code,Class,Remark from OPCParam  order by IndexNo DESC
[2016-11-22 17:58:04.8106] 启动opc失败.
System.NullReferenceException: Object reference not set to an instance of an object.
   at yidascan.FrmMain.StartOpc() in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 81
   at yidascan.FrmMain..ctor() in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 41
[2016-11-22 17:58:04.9666] 初始化失败。
System.NullReferenceException: Object reference not set to an instance of an object.
   at yidascan.FrmMain.BindDgv() in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 97
   at yidascan.FrmMain.FrmMain_Load(Object sender, EventArgs e) in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 58
[2016-11-22 17:58:07.5406] 关闭连接失败！
[2016-11-22 17:58:07.5406] 关闭OPC异常。
System.NullReferenceException: Object reference not set to an instance of an object.
   at ProduceComm.OPC.OPCClient.Close() in E:\ljework\yida\codesource\yidascan\scanner\OPCClient.cs:line 144
   at yidascan.FrmMain.FrmMain_FormClosing(Object sender, FormClosingEventArgs e) in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 782
[2016-11-22 17:58:35.9327] System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at yidascan.DataAccess.DataAccess.Query(String sql, SqlParameter[] p) in E:\ljework\yida\codesource\yidascan\DataAccess\DataAccess.cs:line 56
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20, select IndexNo,Name,Code,Class,Remark from OPCParam  order by IndexNo DESC
[2016-11-22 17:58:36.0107] 启动opc失败.
System.NullReferenceException: Object reference not set to an instance of an object.
   at yidascan.FrmMain.StartOpc() in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 81
   at yidascan.FrmMain..ctor() in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 41
[2016-11-22 17:58:36.1979] 初始化失败。
System.NullReferenceException: Object reference not set to an instance of an object.
   at yidascan.FrmMain.BindDgv() in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 97
   at yidascan.FrmMain.FrmMain_Load(Object sender, EventArgs e) in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 58
[2016-11-22 17:58:45.9323] 关闭连接失败！
[2016-11-22 17:58:45.9323] 关闭OPC异常。
System.NullReferenceException: Object reference not set to an instance of an object.
   at ProduceComm.OPC.OPCClient.Close() in E:\ljework\yida\codesource\yidascan\scanner\OPCClient.cs:line 144
   at yidascan.FrmMain.FrmMain_FormClosing(Object sender, FormClosingEventArgs e) in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 782
[2016-11-22 17:59:16.7580] System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at yidascan.DataAccess.DataAccess.Query(String sql, SqlParameter[] p) in E:\ljework\yida\codesource\yidascan\DataAccess\DataAccess.cs:line 56
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20, select IndexNo,Name,Code,Class,Remark from OPCParam  order by IndexNo DESC
[2016-11-22 17:59:16.8204] 启动opc失败.
System.NullReferenceException: Object reference not set to an instance of an object.
   at yidascan.FrmMain.StartOpc() in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 81
   at yidascan.FrmMain..ctor() in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 41
[2016-11-22 17:59:16.9452] 初始化失败。
System.NullReferenceException: Object reference not set to an instance of an object.
   at yidascan.FrmMain.BindDgv() in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 97
   at yidascan.FrmMain.FrmMain_Load(Object sender, EventArgs e) in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 58
[2016-11-22 17:59:24.5892] 关闭连接失败！
[2016-11-22 17:59:24.5892] 关闭OPC异常。
System.NullReferenceException: Object reference not set to an instance of an object.
   at ProduceComm.OPC.OPCClient.Close() in E:\ljework\yida\codesource\yidascan\scanner\OPCClient.cs:line 144
   at yidascan.FrmMain.FrmMain_FormClosing(Object sender, FormClosingEventArgs e) in E:\ljework\yida\codesource\yidascan\FrmMain.cs:line 782
